### ISSUE TITLE
Messaging Styling Issues

### ISSUE THREAD

**Issue by CaitlinLandrus** [CSC450-Group3/acptheater#155]
Button color probably should be the primary blue color for "New Message" and "Reply"

Reply should probably be first?

If there are too many messages in a thread, the buttons are hidden behind the footer. I think we just need to add height (similar to the movies/showtimes) so the footer is pushed to the bottom and a scrollbar is available.

**Comment by Alexyahn** [comment]
Handling the button color within the other issue "make all buttons antd buttons" only thing left on this one would be too many messages in a thread.
